### ISSUE TITLE
Karma dependencies 

### ISSUE THREAD

**Issue by esettechnical** [ravello/ravello-training#4]
Hi,

I keep having karma dependencies issues while doing a NPm install, I did some digging it seems that it could be due to the package.js. 

Below is my error. I am not very familiar with NPM so can you give me some guide on how to go about this installation? 

npm ERR! peerinvalid The package karma@1.1.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-ng-html2js-preprocessor@0.1.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.6 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.1.6 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-ng-scenario@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@1.0.0 wants karma@>=0.9
npm ERR! peerinvalid Peer grunt-karma@0.6.2 wants karma@~0.10.0
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.1.3 wants karma@>=0.9

**Comment by benbracha** [comment]
Hi @esettechnical 
We accidentally did some partial upgrade of one of the npm packages, which caused this issue.
We just revert this. Please try to pull and try again.
Sorry for that.
